services:
  postgres:
    container_name: ${CONTAINER_NAME}
    image: ${CONTAINER_IMAGE}
    restart: ${CONTAINER_RESTART}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${VOLUME_NAME}:/var/lib/postgresql/data
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - net_postgres

networks:
  net_postgres:
    name: ${NETWORK_NAME}
